<?php
    if (sizeof($this->menuButtons))
        $this->menuBar($this->menuButtons);
?>
<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-hover table-condensed">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Módulo</th>
                    <th>Perfil</th>
                    <th>Descrição do perfil</th>
                    <th style="width:125px;"></th>
                </tr>
            </thead>
            <tbody>
                <?php

                    foreach ($this->perfis as $key => $value) {
                        echo "<tr>";
                        echo    "<td>".$value->prf_id."</td>";
                        echo    "<td>".$value->mod_nome."</td>";
                        echo    "<td>".$value->prf_nome."</td>";
                        echo    "<td>".$value->prf_descricao."</td>";
                        echo    "<td>
                                    <a class='btn btn-mini btn-success' href='/admin/perfispermissoes/atribuirpermissoesperfil/".$value->prf_id."'>
                                        <i class='icon-ok-sign'> Atribuir Permissões</i>
                                    </a>
                                </td>";
                    }
                ?>
            </tbody>
        </table>
    </div>
</div>