<div class="row login-wrapper">
    <div class="box">

        <?php
            $message = $this->flashMessage();
            echo strlen($message) > 0 ? $message : '';
        ?>
        
        <h2>Acessar</h2>
        <form action="/application/auth/login" method="post" name="login" id="login">
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-user"></i></span>
              <input name="usr_usuario" type="text" class="form-control" placeholder="Usuário">
            </div>

            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-lock"></i></span>
              <input name="usr_senha" type="password" class="form-control" placeholder="Senha">
            </div>

            <div class="input-group">
                <input name="submit" type="submit" class="btn btn-primary" value="Entrar">
            </div>
        </form>
    </div>
</div>