<?php
    if (sizeof($this->menuButtons))
        $this->menuBar($this->menuButtons);
?>
<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-hover table-condensed">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nome completo</th>
                    <th>Email</th>
                    <th style="width:27px;"></th>
                    <th style="width:27px;"></th>
                </tr>
            </thead>
            <tbody>
                <?php
                    foreach ($usuarios as $key => $value) {
                        echo "<tr>";
                        echo    "<td>".$value->usr_id."</td>";
                        echo    "<td>".$value->usr_nome."</td>";
                        echo    "<td>".$value->usr_email."</td>";
                        echo    "<td>
                                    <a class='btn btn-mini btn-warning' href='/admin/usuarios/update/".$value->usr_id."' data-id='".$value->usr_id."'>
                                        <i class='fa fa-pencil'></i>
                                    </a>
                                </td>";
                        echo    "<td>
                                    <a class='btn btn-mini btn-danger btn-window-confirm' href='#' data-id='".$value->usr_id."'>
                                        <i class='fa fa-trash-o'></i>
                                    </a>
                                </td>";
                        echo "</tr>";
                    }
                ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">

    $(".btn-window-confirm").click(function(e){
        
        var itemSelecionado = $(e.currentTarget).data('id');
        bootbox.confirm("Você tem certeza que deseja excluir esse usuário?", function(result) {
            if (result)
            {
                window.location.href = '/admin/usuarios/delete/' + itemSelecionado;
            }
        });
    });

</script>