<div class="col-md-12">
    <h3>Atualizar Recurso</h3>
    <?php
        echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('rcs_id'));
            echo $this->elementToRow($form->get('rcs_mod_id'));
            echo $this->elementToRow($form->get('rcs_ctr_id'));
            echo $this->elementToRow($form->get('rcs_nome'));
            echo $this->elementToRow($form->get('rcs_descricao'));
            echo $this->elementToRow($form->get('rcs_icone'));
            echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
    ?>
</div>