<div class="col-md-12">
    <h3>Nova Categoria de Recurso</h3>
    <?php
        echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('ctr_id'));
            echo $this->elementToRow($form->get('ctr_nome'));
            echo $this->elementToRow($form->get('ctr_descricao'));
            echo $this->elementToRow($form->get('ctr_icone'));
            echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
    ?>
</div>