<?php
    if (sizeof($this->menuButtons))
        $this->menuBar($this->menuButtons);
?>
<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-hover table-condensed">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Módulo</th>
                    <th>Perfil</th>
                    <th>Descrição do perfil</th>
                    <th style="width:27px;"></th>
                    <th style="width:27px;"></th>
                </tr>
            </thead>
            <tbody>
                <?php

                    foreach ($this->perfis as $key => $value) {
                        echo "<tr>";
                        echo    "<td>".$value->prf_id."</td>";
                        echo    "<td>".$value->mod_nome."</td>";
                        echo    "<td>".$value->prf_nome."</td>";
                        echo    "<td>".$value->prf_descricao."</td>";
                        echo    "<td>
                                    <a class='btn btn-mini btn-warning' href='/admin/perfis/update/".$value->prf_id."' data-id='".$value->prf_id."'>
                                        <i class='fa fa-pencil'></i>
                                    </a>
                                </td>";
                        echo    "<td>
                                    <a class='btn btn-mini btn-danger btn-window-confirm' href='#' data-id='".$value->prf_id."'>
                                        <i class='fa fa-trash-o'></i>
                                    </a>
                                </td>";
                        echo "</tr>";
                    }
                ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">

    $(".btn-window-confirm").click(function(e){
        
        var itemSelecionado = $(e.currentTarget).data('id');
        bootbox.confirm("Você tem certeza que deseja excluir esse perfil?", function(result) {
            if (result)
            {
                window.location.href = '/admin/perfis/delete/' + itemSelecionado;
            }
        });
    });

</script>