<div class="col-md-12">
    <h3>Atualizar Perfil</h3>
    <?php
        echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('prf_id'));
            echo $this->elementToRow($form->get('prf_mod_id'));
            echo $this->elementToRow($form->get('prf_nome'));
            echo $this->elementToRow($form->get('prf_descricao'));
            echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
    ?>
</div>